version: '3.7'
services:
  base:
    image: stackhawk/vuln-graphql-prisma
    container_name: vuln-graphql-prisma
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    entrypoint:
      - docker-entrypoint.sh
